### ISSUE TITLE
Association rule mining question.

### ISSUE THREAD

**Issue by clegoues** [mausotog/ProbModelPaper#6]
Somehow I never caught that the association rules all require two antecedents.  Why is that?

Anyway, in section 4.E.B, we say we have to remove patches from the corpus for training.  Do we do that after training that happens in 4.E.a?  Or before?  If before, move that explanation earlier, perhaps in the text before 4.E.a starts.  If after....explain it to me, because I'm confused.

**Comment by mausotog** [comment]
I built the association rules with the entire corpus. The rules that we obtained as result of this, all have at least 2 antecedents and 1 consequent (not all rules in Apriori have to be like this, but the ones we obtained are like this). Therefore, to make the evaluation fair, I removed all the patches that definitely can't be predicted by these rules. Everything that has less than 3 edits is then discarded by default, because it is impossible that the rules we obtained would predict a patch like that.
Ex:
If the patch we want to predict is:
Delete -> Append

And we have a million rules with 3 edits or more. None of them will be able to predict this patch above because the patch above will never have at least 3 edits. 
I try to explain that in the paper, not as explicit as here because I don't have as much space, but I hope it's clear in the paper too.
